### ISSUE TITLE
aead::seal_in_place only accepts out_suffix_capacity exactly equal to max overhead

### ISSUE THREAD

**Issue by mcginty** [briansmith/ring#291]
Tested against ring 0.3.1 from crates.io.

The `seal_in_place` documentation says "out_suffix_capacity must be at least `key.algorithm.max_overhead_len()`", however it looks like no value works except for exactly `key.algorithm().max_overhead_len()`. I'd prefer if the documentation's version were true since it would mean fewer allocations for me! Also having out_suffix_capacity as an argument isn't so useful if it can only be one thing ;).

**works**:

``` rust
let data = [0u8; 1350];
let out_suffix_capacity = ALGORITHM.max_overhead_len();
let mut in_out = vec![0u8; data.len() + out_suffix_capacity];
aead::seal_in_place(&key, &nonce_bytes,
                    &mut in_out, out_suffix_capacity,
                    &[]).unwrap();
```

**breaks**:

``` rust
let data = [0u8; 1350];
let out_suffix_capacity = ALGORITHM.max_overhead_len() + 1;
let mut in_out = vec![0u8; data.len() + out_suffix_capacity];
aead::seal_in_place(&key, &nonce_bytes,
                    &mut in_out, out_suffix_capacity,
                    &[]).unwrap();
```

**Comment by briansmith** [comment]
I'm guessing the problem is that `slice_as_array_ref_mut!()` fails.

If you can build from the Git version, try this patch:

```
diff --git a/src/aead/aead.rs b/src/aead/aead.rs
index 22e914c..ad83625 100644
--- a/src/aead/aead.rs
+++ b/src/aead/aead.rs
@@ -178,7 +178,8 @@ pub fn seal_in_place(key: &SealingKey, nonce: &[u8], in_out: &mut [u8],
                          .ok_or(error::Unspecified));
     try!(check_per_nonce_max_bytes(in_out_len));
     let (in_out, tag_out) = in_out.split_at_mut(in_out_len);
-    let tag_out = try!(slice_as_array_ref_mut!(tag_out, TAG_LEN));
+    let tag_out =
+        try!(slice_as_array_ref_mut!(&mut tag_out[..TAG_LEN], TAG_LEN));
     try!((key.key.algorithm.seal)(&key.key.ctx_buf, nonce, in_out, tag_out, ad));
     Ok(in_out_len + TAG_LEN)
 }
```

**Comment by briansmith** [comment]
Thanks for the bug report. I agree that things look wrong.

> The seal_in_place documentation says "out_suffix_capacity must be at least key.algorithm.max_overhead_len()",

In fact, this is overly-strict, isn't it. Really it just needs to be large enough to hold whatever tag is generated. However, in all the AEADs supported so far, those values are the same.

> however it looks like no value works except for exactly key.algorithm().max_overhead_len(). I'd prefer if the documentation's version were true since it would mean fewer allocations for me!

Keep in mind that you can always pass a reference to a smaller slice of a larger allocated thing.

> Also having out_suffix_capacity as an argument isn't so useful if it can only be one thing ;).

Without `out_suffix_capacity` one can't determine the length of the input.

Anyway, I agree that I should fix it, assuming it is broken. It will take a bit of time for me to get to this since it will take time to write tests and I'm busy with other things. For now, just pass in a slice of your buffer such that `out_suffix_capacity` will be equal to `max_overhead_len()`.

Thanks again for the report.

**Comment by mcginty** [comment]
Aha! Sorry, I'm new to rust and didn't know its borrow safety allowed you to create a mutable slice reference from another mutable slice reference. Makes sense though. Thanks for that.

But yeah I guess this still stands as an issue due to the disagreement between functionality and documentation :). Thanks for the response!

**Comment by briansmith** [comment]
It's likely that the API signature will change significantly in *ring* 0.7 or so, to resolve this and other usability issues.

**Comment by bdonlan** [comment]
Just confirming that this is still an issue in 0.14.3. Could the API docs at least be updated to reflect the actual behavior?

**Comment by briansmith** [comment]
Please see #805 where I propose to redo the API in a way that (I hope) makes it clearer. Let me know what you think.

**Comment by briansmith** [comment]
Fixed in #805.
